name: Build and deploy

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '56 */4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 0 indicates all history for all branches and tags.

    - name: build and publish
      env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"  
        ./run.sh
